### ISSUE TITLE
Use frame-loop for better performance

### ISSUE THREAD

**Issue by TehShrike** [spacetag/html5-mulg#1]
Using [frame-loop](https://github.com/substack/frame-loop) will let your game ticks will be driven by when the browser says it is ready to draw a frame, rather than the fickleness of the JavaScript timing engine.

**Comment by spacetag** [comment]
Cool, thanks! I also came across https://hacks.mozilla.org/2011/08/animating-with-javascript-from-setinterval-to-requestanimationframe/

What do you think about using one vs the other? Can I use both?

**Comment by TehShrike** [comment]
frame-loop is actually built as a friendly interface for requestAnimationFrame (with a polyfill falling back on setTimeout for environments that don't have requestAnimationFrame).
