### ISSUE TITLE
Basic build step

### ISSUE THREAD

**Issue by TehShrike** [spacetag/html5-mulg#2]
Would you be open to a pull request adding a basic [browserify](http://browserify.org/) build so that you could write modular code instead of appending to a big JS script using globals?  It would make including third-party code a lot easier.

If you're willing, I'll add a pull request that makes it so you would run `npm run watch` when you were developing, and then you could run `npm run build` when you wanted to build a minified version for release, and that would be all you would have to know.

It would make implementing #1 even easier!

**Comment by spacetag** [comment]
Sure, thanks for your help! :-)
:+1: 

Can I still do a live HTML preview from rawgit.com or an equivalent with that?
Maybe I could just have a built version on a gh-pages branch...

**Comment by TehShrike** [comment]
Yeah, that'd probably be the thing to do - for releases, merge into gh-pages, and then run `npm run build`, and commit the `build.js` file.
